resolver ${DNS_RESOLVER} valid=10s ipv6=off;

server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  set $atlas_api tiiv-atlas-api:8080;

  location /api/ {
    proxy_pass http://$atlas_api;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  location /health {
    proxy_pass http://$atlas_api;
  }

  location / {
    try_files $uri /index.html;
  }
}
