SELECT set_config('app.tenant_id',(SELECT id::text FROM tenants WHERE slug='default'),false);
INSERT INTO users(name,email,password_hash,role) VALUES ('Atlas Admin','admin@tiiv.local',crypt('atlas123',gen_salt('bf')),'superadmin') ON CONFLICT(email) DO NOTHING;
WITH s AS (INSERT INTO sites(name,slug,description) VALUES ('Datacenter New Life','datacenter-new-life','Primary infrastructure site') ON CONFLICT(tenant_id,slug) DO UPDATE SET name=excluded.name RETURNING id),
r AS (INSERT INTO rooms(site_id,name,description) SELECT id,'Sala Principal','Core and server room' FROM s ON CONFLICT(site_id,name) DO UPDATE SET description=excluded.description RETURNING id),
rk AS (INSERT INTO racks(site_id,room_id,name,description,rack_units) SELECT s.id,r.id,'RACK-CORE-01','Primary network rack',42 FROM s,r ON CONFLICT(site_id,name) DO UPDATE SET room_id=excluded.room_id RETURNING id)
SELECT 1;
INSERT INTO manufacturers(name) VALUES ('MikroTik'),('Huawei'),('Dell'),('FiberHome') ON CONFLICT(tenant_id,name) DO NOTHING;
DO $$ DECLARE s uuid; r uuid; mid uuid; d1 uuid;d2 uuid;d3 uuid;d4 uuid;d5 uuid;p1 uuid;p2 uuid;p3 uuid;p4 uuid;p5 uuid;p6 uuid; BEGIN
SELECT id INTO s FROM sites WHERE tenant_id=current_setting('app.tenant_id')::uuid AND slug='datacenter-new-life'; SELECT id INTO r FROM racks WHERE tenant_id=current_setting('app.tenant_id')::uuid AND site_id=s AND name='RACK-CORE-01';
SELECT id INTO mid FROM manufacturers WHERE tenant_id=current_setting('app.tenant_id')::uuid AND name='MikroTik'; INSERT INTO devices(name,manufacturer_id,device_type,site_id,rack_id,rack_position,rack_height,management_ip,status,description) VALUES('ROUTER-EDGE',mid,'router',s,r,42,1,'10.10.0.1','active','Internet edge') ON CONFLICT(site_id,name) DO UPDATE SET name=excluded.name RETURNING id INTO d1;
SELECT id INTO mid FROM manufacturers WHERE tenant_id=current_setting('app.tenant_id')::uuid AND name='Huawei'; INSERT INTO devices(name,manufacturer_id,device_type,site_id,rack_id,rack_position,rack_height,management_ip,status) VALUES('SW-CORE-01',mid,'switch',s,r,40,1,'10.10.0.2','active') ON CONFLICT(site_id,name) DO UPDATE SET name=excluded.name RETURNING id INTO d2; INSERT INTO devices(name,manufacturer_id,device_type,site_id,rack_id,rack_position,rack_height,management_ip,status) VALUES('SW-ACCESS-01',mid,'switch',s,r,38,1,'10.10.0.3','active') ON CONFLICT(site_id,name) DO UPDATE SET name=excluded.name RETURNING id INTO d3;
SELECT id INTO mid FROM manufacturers WHERE tenant_id=current_setting('app.tenant_id')::uuid AND name='Dell'; INSERT INTO devices(name,manufacturer_id,device_type,site_id,rack_id,rack_position,rack_height,management_ip,status) VALUES('PROXMOX-01',mid,'server',s,r,29,2,'10.10.0.10','active') ON CONFLICT(site_id,name) DO UPDATE SET name=excluded.name RETURNING id INTO d4;
SELECT id INTO mid FROM manufacturers WHERE tenant_id=current_setting('app.tenant_id')::uuid AND name='FiberHome'; INSERT INTO devices(name,manufacturer_id,device_type,site_id,rack_id,rack_position,rack_height,management_ip,status) VALUES('OLT-01',mid,'olt',s,r,20,2,'10.10.0.20','maintenance') ON CONFLICT(site_id,name) DO UPDATE SET name=excluded.name RETURNING id INTO d5;
INSERT INTO device_ports(device_id,name,type,speed) VALUES(d1,'SFP1','sfp_plus','10G') ON CONFLICT(device_id,name) DO UPDATE SET speed=excluded.speed RETURNING id INTO p1; INSERT INTO device_ports(device_id,name,type,speed) VALUES(d2,'XGE0/0/1','sfp_plus','10G') ON CONFLICT(device_id,name) DO UPDATE SET speed=excluded.speed RETURNING id INTO p2; INSERT INTO device_ports(device_id,name,type,speed) VALUES(d2,'XGE0/0/2','sfp_plus','10G') ON CONFLICT(device_id,name) DO UPDATE SET speed=excluded.speed RETURNING id INTO p3; INSERT INTO device_ports(device_id,name,type,speed) VALUES(d3,'SFP1','sfp_plus','10G') ON CONFLICT(device_id,name) DO UPDATE SET speed=excluded.speed RETURNING id INTO p4; INSERT INTO device_ports(device_id,name,type,speed) VALUES(d2,'XGE0/0/4','sfp_plus','10G') ON CONFLICT(device_id,name) DO UPDATE SET speed=excluded.speed RETURNING id INTO p5; INSERT INTO device_ports(device_id,name,type,speed) VALUES(d4,'eno1','ethernet','10G') ON CONFLICT(device_id,name) DO UPDATE SET speed=excluded.speed RETURNING id INTO p6;
INSERT INTO cables(port_a_id,port_b_id,label,cable_type,color) VALUES(p1,p2,'EDGE-CORE','fiber_sm','#22c55e'),(p3,p4,'CORE-ACCESS','fiber_sm','#3b82f6'),(p5,p6,'CORE-PROXMOX','dac','#a855f7') ON CONFLICT DO NOTHING;
END $$;
INSERT INTO networks(site_id,prefix,name,gateway) SELECT id,'10.10.0.0/24','Management','10.10.0.1' FROM sites WHERE tenant_id=current_setting('app.tenant_id')::uuid AND slug='datacenter-new-life' ON CONFLICT(tenant_id,prefix) DO NOTHING; INSERT INTO networks(site_id,prefix,name,gateway) SELECT id,'10.20.0.0/24','Servers','10.20.0.1' FROM sites WHERE tenant_id=current_setting('app.tenant_id')::uuid AND slug='datacenter-new-life' ON CONFLICT(tenant_id,prefix) DO NOTHING; INSERT INTO networks(site_id,prefix,name,gateway) SELECT id,'10.30.0.0/24','Storage','10.30.0.1' FROM sites WHERE tenant_id=current_setting('app.tenant_id')::uuid AND slug='datacenter-new-life' ON CONFLICT(tenant_id,prefix) DO NOTHING;
INSERT INTO vlans(site_id,vid,name) SELECT id,v.vid,v.name FROM sites CROSS JOIN (VALUES(10,'Management'),(20,'Servers'),(30,'Storage')) v(vid,name) WHERE tenant_id=current_setting('app.tenant_id')::uuid AND slug='datacenter-new-life' ON CONFLICT(tenant_id,site_id,vid) DO NOTHING;
