import {useEffect,useState} from 'react';
import {Globe2,Plus,Server,X} from 'lucide-react';
import {api,type Device} from './lib/api';
import {RowMenu} from './RowMenu';
type Network={id:string;prefix:string;name:string};
type IPAddress={id:string;network_id?:string;address:string;device_id?:string;assigned_to?:string;dns_name?:string;description?:string;status:string};
const emptyForm={network_id:'',address:'',device_id:'',assigned_to:'',dns_name:'',description:'',status:'active'};
export function IPAddressesPage(){
  const [ips,setIPs]=useState<IPAddress[]>([]),[networks,setNetworks]=useState<Network[]>([]),[devices,setDevices]=useState<Device[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<IPAddress|null>(null),[error,setError]=useState('');
  const [form,setForm]=useState(emptyForm);
  const load=()=>Promise.all([api<IPAddress[]>('/ip-addresses'),api<Network[]>('/networks'),api<Device[]>('/devices')]).then(([i,n,d])=>{setIPs(i);setNetworks(n);setDevices(d);setForm(f=>({...f,network_id:f.network_id||n[0]?.id||''}))}).catch(e=>setError(e.message));
  useEffect(()=>{void load()},[]);
  const startCreate=()=>{setEditing(null);setForm(()=>({...emptyForm,network_id:networks[0]?.id||''}));setError('');setOpen(true)};
  const startEdit=(ip:IPAddress)=>{setEditing(ip);setForm({network_id:ip.network_id||'',address:ip.address,device_id:ip.device_id||'',assigned_to:ip.assigned_to||'',dns_name:ip.dns_name||'',description:ip.description||'',status:ip.status});setError('');setOpen(true)};
  const save=async()=>{setError('');try{const body=editing?{...form,network_id:form.network_id||null,device_id:form.device_id||null,assigned_to:form.assigned_to||null}:Object.fromEntries(Object.entries(form).filter(([,v])=>v!==''));if(editing)await api(`/ip-addresses/${editing.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/ip-addresses',{method:'POST',body:JSON.stringify(body)});setOpen(false);setForm(f=>({...f,address:'',assigned_to:'',dns_name:'',description:''}));load()}catch(e){setError(e instanceof Error?e.message:'Could not save IP address')}};
  const remove=async(ip:IPAddress)=>{if(!confirm(`Delete ${ip.address}?`))return;try{await api(`/ip-addresses/${ip.id}`,{method:'DELETE'});load()}catch(e){setError(e instanceof Error?e.message:'Could not delete IP address')}};
  return <><div className="page-head"><div><h1>IP Addresses</h1><p>Assign documented addresses to a device, or just a client name.</p></div><button className="primary" onClick={startCreate}><Plus size={16}/>Assign IP</button></div>
    {error&&!open&&<div className="form-error page-error">{error}</div>}
    <section className="panel">{ips.length===0?<div className="resource-empty"><Globe2/><h2>No assigned addresses</h2><p>Open a network's address grid, or assign one here directly.</p><button className="primary" onClick={startCreate}><Plus size={15}/>Assign IP</button></div>:<div className="table-wrap"><table><thead><tr><th>IP address</th><th>Network</th><th>Assigned to</th><th>DNS name</th><th>Status</th><th/></tr></thead><tbody>{ips.map(ip=>{const device=devices.find(d=>d.id===ip.device_id);return <tr key={ip.id}><td className="mono linkish">{ip.address}</td><td>{networks.find(n=>n.id===ip.network_id)?.name??'—'}<small className="cell-detail">{networks.find(n=>n.id===ip.network_id)?.prefix}</small></td><td>{device?<span className="resource-name"><Server/><strong>{device.name}</strong></span>:ip.assigned_to?<strong>{ip.assigned_to}</strong>:<span className="cell-detail">Unassigned</span>}</td><td>{ip.dns_name||'—'}</td><td><span className={'status '+ip.status}><i/>{ip.status}</span></td><td><RowMenu items={[{label:'Edit address',onClick:()=>startEdit(ip)},{label:'Delete address',danger:true,onClick:()=>void remove(ip)}]}/></td></tr>})}</tbody></table></div>}</section>
    {open&&<div className="modal-backdrop"><div className="resource-modal"><header><div><h2>{editing?'Edit IP address':'Assign IP address'}</h2><p>Attach an address to a device, or just note who it was handed to.</p></div><button onClick={()=>setOpen(false)}><X/></button></header><div className="resource-form"><label>Network<select value={form.network_id} onChange={e=>setForm(f=>({...f,network_id:e.target.value}))}>{networks.map(n=><option key={n.id} value={n.id}>{n.name} · {n.prefix}</option>)}</select></label><label>IP address<input autoFocus value={form.address} onChange={e=>setForm(f=>({...f,address:e.target.value}))} placeholder="10.10.0.25"/></label><label>Device (optional)<select value={form.device_id} onChange={e=>setForm(f=>({...f,device_id:e.target.value}))}><option value="">No device</option>{devices.map(d=><option key={d.id} value={d.id}>{d.name} · {d.device_type}</option>)}</select></label><label>Assigned to / client (optional)<input value={form.assigned_to} onChange={e=>setForm(f=>({...f,assigned_to:e.target.value}))} placeholder="Customer or contact name"/></label><label>DNS name (optional)<input value={form.dns_name} onChange={e=>setForm(f=>({...f,dns_name:e.target.value}))} placeholder="switch-01.example.local"/></label><label>Status<select value={form.status} onChange={e=>setForm(f=>({...f,status:e.target.value}))}><option value="active">Active</option><option value="reserved">Reserved</option><option value="available">Available</option><option value="deprecated">Deprecated</option></select></label><label>Notes<textarea value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))}/></label>{error&&<div className="form-error">{error}</div>}</div><footer><button className="cancel" onClick={()=>setOpen(false)}>Cancel</button><button className="primary" disabled={!form.address||(form.status==='active'&&!form.device_id&&!form.assigned_to.trim())} onClick={save}>{editing?'Save changes':'Assign address'}</button></footer></div></div>}
  </>;
}
