import {useEffect,useMemo,useState} from 'react';
import {Cable,Plus,X,Zap} from 'lucide-react';
import {api} from './lib/api';
type Site={id:string;name:string}; type Rack={id:string;site_id:string;name:string};
type Link={port_name:string;target_device_name:string;target_port_name:string;cable_type:string;label:string};
type PortGroup={id:string;prefix:string;count:number;type:string;speed:string};
const PORT_TYPES=['ethernet','sfp','sfp_plus','fiber','wireless','other'];
const newGroup=():PortGroup=>({id:crypto.randomUUID(),prefix:'',count:0,type:'ethernet',speed:''});
export function QuickInstall({onClose}:{onClose:()=>void}){
 const [sites,setSites]=useState<Site[]>([]),[racks,setRacks]=useState<Rack[]>([]),[links,setLinks]=useState<Link[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const [portGroups,setPortGroups]=useState<PortGroup[]>([{id:crypto.randomUUID(),prefix:'Gi1/0/',count:24,type:'ethernet',speed:'1G'}]);
 const [f,setF]=useState({name:'',manufacturer:'',model:'',device_type:'switch',purpose:'',site_id:'',rack_id:'',rack_position:1,rack_height:1,management_ip:'',status:'active',power_supply_count:1,power_input_voltage:'AC 220V',power_capacity_watts:0});
 useEffect(()=>{Promise.all([api<Site[]>('/sites'),api<Rack[]>('/racks')]).then(([s,r])=>{setSites(s);setRacks(r);setF(v=>({...v,site_id:s[0]?.id??'',rack_id:r[0]?.id??''}))}).catch(e=>setError(e.message))},[]);
 const ports=useMemo(()=>[...portGroups.flatMap(g=>Array.from({length:g.count||0},(_,i)=>({name:`${g.prefix}${i+1}`,type:g.type,speed:g.speed}))),...Array.from({length:f.power_supply_count||0},(_,i)=>({name:`PSU${i+1}`,type:'power',speed:f.power_input_voltage}))],[portGroups,f.power_supply_count,f.power_input_voltage]);
 const duplicateNames=useMemo(()=>{const seen=new Map<string,number>();ports.forEach(p=>seen.set(p.name,(seen.get(p.name)||0)+1));return[...seen.entries()].filter(([,c])=>c>1).map(([n])=>n)},[ports]);
 const set=(k:string,v:string|number)=>setF(x=>({...x,[k]:v}));
 const changeLink=(i:number,k:keyof Link,v:string)=>setLinks(a=>a.map((x,n)=>n===i?{...x,[k]:v}:x));
 const changeGroup=(i:number,k:keyof PortGroup,v:string|number)=>setPortGroups(a=>a.map((x,n)=>n===i?{...x,[k]:v}:x));
 const addGroup=()=>setPortGroups(a=>[...a,newGroup()]);
 const removeGroup=(i:number)=>setPortGroups(a=>a.filter((_,n)=>n!==i));
 const save=async()=>{setBusy(true);setError('');try{await api('/devices/quick-create',{method:'POST',body:JSON.stringify({...f,ports:ports.filter(p=>p.type!=='power'),connections:links})});onClose();location.href='/devices'}catch(e){setError(e instanceof Error?e.message:'Installation failed')}finally{setBusy(false)}};
 return <div className="modal-backdrop"><div className="quick-install"><header className="quick-head"><div><span><Zap/></span><div><h2>Install device</h2><p>Equipment, purpose, ports and cables in one flow.</p></div></div><button onClick={onClose}><X/></button></header><div className="quick-body">
 <Block n="1" title="Equipment and purpose" help="Type a manufacturer and model here. Atlas creates them automatically."><div className="form-grid"><Field wide label="Device name"><input autoFocus value={f.name} onChange={e=>set('name',e.target.value)} placeholder="SW-DISTRIBUTION-01"/></Field><Field label="Manufacturer"><input value={f.manufacturer} onChange={e=>set('manufacturer',e.target.value)} placeholder="Huawei"/></Field><Field label="Model"><input value={f.model} onChange={e=>set('model',e.target.value)} placeholder="S6730-H24X6C"/></Field><Field label="Device type"><select value={f.device_type} onChange={e=>set('device_type',e.target.value)}>{['switch','router','server','firewall','olt','patch_panel','pdu','ups','rectifier','inverter','battery_bank','generator','transfer_switch','other'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Purpose / use"><input value={f.purpose} onChange={e=>set('purpose',e.target.value)} placeholder="Core, access, virtualization…"/></Field></div></Block>
 <Block n="2" title="Placement and management" help="Place it in the rack and assign its address now."><div className="form-grid"><Field label="Site"><select value={f.site_id} onChange={e=>set('site_id',e.target.value)}>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Rack"><select value={f.rack_id} onChange={e=>set('rack_id',e.target.value)}><option value="">No rack</option>{racks.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><Field label="Rack unit"><input type="number" min="1" value={f.rack_position} onChange={e=>set('rack_position',+e.target.value)}/></Field><Field label="Height"><input type="number" min="1" value={f.rack_height} onChange={e=>set('rack_height',+e.target.value)}/></Field><Field label="Management IP (optional)"><input value={f.management_ip} onChange={e=>set('management_ip',e.target.value)} placeholder="10.10.0.4"/>{f.management_ip&&<span className="ipam-hint">Atlas will validate the network and assign this address in IPAM.</span>}</Field><Field label="Status"><select value={f.status} onChange={e=>set('status',e.target.value)}><option value="active">Active</option><option value="planned">Planned</option><option value="maintenance">Maintenance</option></select></Field></div></Block>
 <Block n="3" title="Ports and power" help={`${ports.length-(f.power_supply_count||0)} data ports and ${f.power_supply_count||0} PSU will be ready when the device is saved.`}>
 <div className="subsection-title"><h4>Power supplies</h4></div>
 <div className="power-builder"><Field label="How many PSUs"><input type="number" min="0" max="8" value={f.power_supply_count} onChange={e=>set('power_supply_count',Math.max(0,Math.min(8,+e.target.value)))}/></Field><Field label="Voltage (per PSU)"><input value={f.power_input_voltage} onChange={e=>set('power_input_voltage',e.target.value)} placeholder="AC 220V or DC -48V"/></Field><Field label="Capacity (W, per PSU)"><input type="number" min="0" value={f.power_capacity_watts} onChange={e=>set('power_capacity_watts',+e.target.value)}/></Field></div>
 {f.power_supply_count>0&&<div className="port-preview">{Array.from({length:f.power_supply_count},(_,i)=><span key={i}>PSU{i+1}</span>)}</div>}
 <div className="subsection-title"><h4>Ports</h4><button type="button" className="add-link" onClick={addGroup}><Plus/> Add port group</button></div>
 <p className="section-hint">One group per port kind — e.g. 24 copper ports, then a second group of 4 SFP+ uplinks.</p>
 <div className="port-groups">{portGroups.map((g,i)=>{const names=Array.from({length:g.count||0},(_,n)=>`${g.prefix}${n+1}`);return <div className="port-group" key={g.id}>
 <div className="port-builder"><Field label="Prefix"><input value={g.prefix} onChange={e=>changeGroup(i,'prefix',e.target.value)} placeholder="Gi1/0/"/></Field><Field label="Quantity"><input type="number" min="0" max="256" value={g.count} onChange={e=>changeGroup(i,'count',+e.target.value)}/></Field><Field label="Type"><select value={g.type} onChange={e=>changeGroup(i,'type',e.target.value)}>{PORT_TYPES.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Speed"><input value={g.speed} onChange={e=>changeGroup(i,'speed',e.target.value)} placeholder="1G"/></Field>{portGroups.length>1&&<button type="button" className="remove-group" title="Remove group" onClick={()=>removeGroup(i)}><X/></button>}</div>
 <div className="port-preview">{names.length===0?<em>No ports in this group yet</em>:<>{names.slice(0,6).map(n=><span key={n}>{n}</span>)}{names.length>6&&<em>+{names.length-6}</em>}</>}</div>
 </div>})}</div>
 {duplicateNames.length>0&&<div className="form-error">Duplicate port names: {duplicateNames.join(', ')}. Change the prefixes so every port has a unique name.</div>}
 </Block>
 <Block n="4" title="Start cabling" help="Optional: connect new ports to equipment already documented."><button className="add-link" onClick={()=>setLinks(a=>[...a,{port_name:ports[0]?.name??'',target_device_name:'',target_port_name:'',cable_type:'cat6',label:''}])}><Plus/> Add cable</button>{links.length===0?<div className="empty-cable"><Cable/> Save now or add the first physical connection.</div>:<div className="cable-rows">{links.map((l,i)=><div className="cable-row" key={i}><select value={l.port_name} onChange={e=>changeLink(i,'port_name',e.target.value)}>{ports.map(p=><option key={p.name}>{p.name}</option>)}</select><i>→</i><input placeholder="Target device" value={l.target_device_name} onChange={e=>changeLink(i,'target_device_name',e.target.value)}/><input placeholder="Target port" value={l.target_port_name} onChange={e=>changeLink(i,'target_port_name',e.target.value)}/><select value={l.cable_type} onChange={e=>changeLink(i,'cable_type',e.target.value)}><option value="cat6">CAT6</option><option value="fiber_sm">Fiber SM</option><option value="fiber_mm">Fiber MM</option><option value="dac">DAC</option><option value="wireless">Wireless</option><option value="power">Power</option></select><button onClick={()=>setLinks(a=>a.filter((_,n)=>n!==i))}><X/></button></div>)}</div>}</Block>
 {error&&<div className="form-error">{error}</div>}</div><footer className="quick-footer"><span>One save creates everything.</span><div><button className="cancel" onClick={onClose}>Cancel</button><button className="primary" disabled={busy||!f.name||!f.manufacturer||!f.model||duplicateNames.length>0} onClick={save}>{busy?'Installing…':'Install device'}</button></div></footer></div></div>
}
function Block({n,title,help,children}:{n:string;title:string;help:string;children:React.ReactNode}){return <section><div className="section-title"><b>{n}</b><div><h3>{title}</h3><p>{help}</p></div></div>{children}</section>}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?'span2':''}>{label}{children}</label>}
