import {useEffect,useState} from 'react';
import {Building2,DoorOpen,MapPin,Plus,X} from 'lucide-react';
import {api} from './lib/api';
import {RowMenu} from './RowMenu';
type Site={id:string;name:string;slug:string;description:string;address_line?:string;city?:string;state?:string;country?:string;postal_code?:string;latitude?:string;longitude?:string}; type Room={id:string;site_id:string;name:string;description:string};
const emptySite={name:'',slug:'',description:'',address_line:'',city:'',state:'',country:'',postal_code:'',latitude:'',longitude:''};
const emptyRoom={site_id:'',name:'',description:''};
const Head=({title,description,action,onAction}:{title:string;description:string;action:string;onAction:()=>void})=><div className="page-head"><div><h1>{title}</h1><p>{description}</p></div><button className="primary" onClick={onAction}><Plus size={16}/>{action}</button></div>;
const Empty=({kind,onAdd}:{kind:string;onAdd:()=>void})=><div className="resource-empty"><MapPin/><h2>No {kind} yet</h2><p>Create the first one to organize your infrastructure.</p><button className="primary" onClick={onAdd}><Plus size={15}/>Add {kind.slice(0,-1)}</button></div>;

export function SitesPage(){
  const [items,setItems]=useState<Site[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<Site|null>(null),[error,setError]=useState('');
  const [form,setForm]=useState(emptySite);
  const load=()=>api<Site[]>('/sites?page_size=100').then(setItems).catch(e=>setError(e.message));
  useEffect(()=>{void load()},[]);
  const startCreate=()=>{setEditing(null);setForm(emptySite);setError('');setOpen(true)};
  const startEdit=(s:Site)=>{setEditing(s);setForm({name:s.name,slug:s.slug,description:s.description||'',address_line:s.address_line||'',city:s.city||'',state:s.state||'',country:s.country||'',postal_code:s.postal_code||'',latitude:s.latitude||'',longitude:s.longitude||''});setError('');setOpen(true)};
  const save=async()=>{try{const body=editing?{...form,latitude:form.latitude||null,longitude:form.longitude||null}:Object.fromEntries(Object.entries(form).filter(([,v])=>v!==''));if(editing)await api(`/sites/${editing.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/sites',{method:'POST',body:JSON.stringify(body)});setOpen(false);load()}catch(e){setError(e instanceof Error?e.message:'Could not save site')}};
  const remove=async(s:Site)=>{if(!confirm(`Delete ${s.name}? Rooms and racks in this site keep their records but lose their site link only if you remove them first.`))return;try{await api(`/sites/${s.id}`,{method:'DELETE'});load()}catch(e){setError(e instanceof Error?e.message:'Could not delete site — it may still have rooms, racks, or devices')}};
  return <><Head title="Sites" description="Datacenters, POPs, offices and infrastructure locations." action="Add site" onAction={startCreate}/>
    {error&&!open&&<div className="form-error page-error">{error}</div>}
    <section className="panel">{items.length===0?<Empty kind="sites" onAdd={startCreate}/>:<div className="resource-grid">{items.map(s=><article key={s.id}><span><Building2/></span><div><h3>{s.name}</h3><p>{s.description||'No description'}</p><small>{s.slug}</small><SiteLocation site={s}/></div><RowMenu items={[{label:'Edit site',onClick:()=>startEdit(s)},{label:'Delete site',danger:true,onClick:()=>void remove(s)}]}/></article>)}</div>}</section>
    {open&&<Modal title={editing?'Edit site':'Add site'} close={()=>setOpen(false)} save={save} error={error} saveLabel={editing?'Save changes':'Save'}><label>Site name<input autoFocus value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value,slug:editing?f.slug:slugify(e.target.value)}))} placeholder="Datacenter New Life"/></label><label>Slug<input value={form.slug} onChange={e=>setForm(f=>({...f,slug:e.target.value}))}/></label><label>Description<textarea value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))}/></label><div className="form-subtitle">Optional location</div><label>Address<input value={form.address_line} onChange={e=>setForm(f=>({...f,address_line:e.target.value}))} placeholder="Street, number and district"/></label><div className="form-row"><label>City<input value={form.city} onChange={e=>setForm(f=>({...f,city:e.target.value}))}/></label><label>State<input value={form.state} onChange={e=>setForm(f=>({...f,state:e.target.value}))}/></label></div><div className="form-row"><label>Country<input value={form.country} onChange={e=>setForm(f=>({...f,country:e.target.value}))} placeholder="Brazil"/></label><label>Postal code<input value={form.postal_code} onChange={e=>setForm(f=>({...f,postal_code:e.target.value}))}/></label></div><div className="form-row"><label>Latitude<input type="number" step="any" min="-90" max="90" value={form.latitude} onChange={e=>setForm(f=>({...f,latitude:e.target.value}))} placeholder="-23.550520"/></label><label>Longitude<input type="number" step="any" min="-180" max="180" value={form.longitude} onChange={e=>setForm(f=>({...f,longitude:e.target.value}))} placeholder="-46.633308"/></label></div></Modal>}
  </>;
}

export function RoomsPage(){
  const [rooms,setRooms]=useState<Room[]>([]),[sites,setSites]=useState<Site[]>([]),[open,setOpen]=useState(false),[editing,setEditing]=useState<Room|null>(null),[error,setError]=useState('');
  const [form,setForm]=useState(emptyRoom);
  const load=()=>Promise.all([api<Room[]>('/rooms?page_size=100'),api<Site[]>('/sites?page_size=100')]).then(([r,s])=>{setRooms(r);setSites(s);setForm(f=>({...f,site_id:f.site_id||s[0]?.id||''}))}).catch(e=>setError(e.message));
  useEffect(()=>{void load()},[]);
  const startCreate=()=>{setEditing(null);setForm(()=>({...emptyRoom,site_id:sites[0]?.id||''}));setError('');setOpen(true)};
  const startEdit=(r:Room)=>{setEditing(r);setForm({site_id:r.site_id,name:r.name,description:r.description||''});setError('');setOpen(true)};
  const save=async()=>{try{const body=editing?form:Object.fromEntries(Object.entries(form).filter(([,v])=>v!==''));if(editing)await api(`/rooms/${editing.id}`,{method:'PUT',body:JSON.stringify(body)});else await api('/rooms',{method:'POST',body:JSON.stringify(body)});setOpen(false);load()}catch(e){setError(e instanceof Error?e.message:'Could not save room')}};
  const remove=async(r:Room)=>{if(!confirm(`Delete ${r.name}?`))return;try{await api(`/rooms/${r.id}`,{method:'DELETE'});load()}catch(e){setError(e instanceof Error?e.message:'Could not delete room')}};
  return <><Head title="Rooms" description="Physical areas within each site." action="Add room" onAction={startCreate}/>
    {error&&!open&&<div className="form-error page-error">{error}</div>}
    <section className="panel">{rooms.length===0?<Empty kind="rooms" onAdd={startCreate}/>:<div className="table-wrap"><table><thead><tr><th>Room</th><th>Site</th><th>Description</th><th/></tr></thead><tbody>{rooms.map(r=><tr key={r.id}><td><span className="resource-name"><DoorOpen/><strong>{r.name}</strong></span></td><td>{sites.find(s=>s.id===r.site_id)?.name??'—'}</td><td>{r.description||'—'}</td><td><RowMenu items={[{label:'Edit room',onClick:()=>startEdit(r)},{label:'Delete room',danger:true,onClick:()=>void remove(r)}]}/></td></tr>)}</tbody></table></div>}</section>
    {open&&<Modal title={editing?'Edit room':'Add room'} close={()=>setOpen(false)} save={save} error={error} saveLabel={editing?'Save changes':'Save'}><label>Site<select value={form.site_id} onChange={e=>setForm(f=>({...f,site_id:e.target.value}))}>{sites.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Room name<input autoFocus value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))} placeholder="Main room"/></label><label>Description<textarea value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))}/></label></Modal>}
  </>;
}

function SiteLocation({site}:{site:Site}){const address=[site.address_line,site.city,site.state,site.country].filter(Boolean).join(', ');return <>{address&&<p className="site-address"><MapPin/>{address}</p>}{site.latitude&&site.longitude&&<a className="map-link" href={`https://www.openstreetmap.org/?mlat=${site.latitude}&mlon=${site.longitude}#map=16/${site.latitude}/${site.longitude}`} target="_blank" rel="noreferrer">View coordinates</a>}</>}
export function Modal({title,close,save,error,saveLabel='Save',children}:{title:string;close:()=>void;save:()=>void;error:string;saveLabel?:string;children:React.ReactNode}){return <div className="modal-backdrop"><div className="resource-modal"><header><div><h2>{title}</h2><p>Only the essential information.</p></div><button onClick={close}><X/></button></header><div className="resource-form">{children}{error&&<div className="form-error">{error}</div>}</div><footer><button className="cancel" onClick={close}>Cancel</button><button className="primary" onClick={save}>{saveLabel}</button></footer></div></div>}
export const slugify=(v:string)=>v.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
